### ISSUE TITLE
Running a complete pipeline for training gnns with real data without errors

### ISSUE THREAD

**Issue by gcroci2** [DeepRank/deeprank-core#103]
Code I'm using: 

python
```
import torch.nn as nn
import h5py
import torch
from deeprank_gnn.DataSet import HDF5DataSet
from deeprank_gnn.NeuralNet import NeuralNet
import numpy as np
from deeprank_gnn.ginet import GINet

database = '/Users/giuliacrocioni/remote_snellius/data/pMHCI/gnn_hdf5/rd.hdf5'
node_features = ["bsa", "depth", "hb_acceptors", "hb_donors", "hse", "ic", "pssm", "polarity", "sasa", "size", "type"]
edge_features = ["coulomb", "covalent", "dist", "vanderwaals"]

if __name__ == '__main__':

    # creating HDF5DataSet object and selecting molecules, node/edge features, target, and clustering method:
    dataset = HDF5DataSet(
        root = "./",
        database = database,
        node_feature = node_features,
        edge_feature = edge_features,
        target = "binary",
        clustering_method = None
    )

    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

    nn = NeuralNet(
        dataset,
        GINet,
        task = "class",
        batch_size = 16,
        percent = [0.8, 0.2]
    )

    nn.train(nepoch = 5, validate = True)
```

Error that I get: 
```
Traceback (most recent call last):
  File "/Users/giuliacrocioni/miniforge3/envs/3d_vac/lib/python3.10/site-packages/torch_geometric/data/storage.py", line 50, in __getattr__
    return self[key]
  File "/Users/giuliacrocioni/miniforge3/envs/3d_vac/lib/python3.10/site-packages/torch_geometric/data/storage.py", line 70, in __getitem__
    return self._mapping[key]
KeyError: 'cluster0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/giuliacrocioni/Desktop/eScience/projects_2022/3D-vac/3D-Vac/src/models/gnn_training.py", line 93, in <module>
    nn.train(nepoch = 5, validate = True)
  File "/Users/giuliacrocioni/Desktop/eScience/projects_2022/3D-vac/deeprank-gnn-2/deeprank_gnn/NeuralNet.py", line 301, in train
    self.eval(self.train_loader, 0, "training")
  File "/Users/giuliacrocioni/Desktop/eScience/projects_2022/3D-vac/deeprank-gnn-2/deeprank_gnn/NeuralNet.py", line 412, in eval
    pred = self.model(data_batch)
  File "/Users/giuliacrocioni/miniforge3/envs/3d_vac/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/giuliacrocioni/Desktop/eScience/projects_2022/3D-vac/deeprank-gnn-2/deeprank_gnn/ginet.py", line 91, in forward
    cluster = get_preloaded_cluster(data.cluster0, data.batch)
  File "/Users/giuliacrocioni/miniforge3/envs/3d_vac/lib/python3.10/site-packages/torch_geometric/data/data.py", line 362, in __getattr__
    return getattr(self._store, key)
  File "/Users/giuliacrocioni/miniforge3/envs/3d_vac/lib/python3.10/site-packages/torch_geometric/data/storage.py", line 52, in __getattr__
    raise AttributeError(
AttributeError: 'GlobalStorage' object has no attribute 'cluster0'
```

**Comment by gcroci2** [comment]
@cbaakman any idea about it?

**Comment by cbaakman** [comment]
Looks like you're using the ScatterPlotExporter in combination with binary classification. (output: n x 2, target: n x 1)
The ScatterPlotExporter was designed for regression. (output: n x 1, target: n x 1)

Such a mistake is detectable before running NeuralNet.train. Shall we throw an error message if that happens?
