### ISSUE TITLE
Fix TensorboardBinaryClassificationExporter that gives a zero-division like error

### ISSUE THREAD

**Issue by gcroci2** [DeepRank/deeprank-core#112]
The code I am using:

```
import torch.nn as nn
import h5py
import torch
from deeprankcore.DataSet import HDF5DataSet
from deeprankcore.NeuralNet import NeuralNet
import numpy as np
from deeprankcore.ginet import GINet
from deeprankcore.models.metrics import OutputExporter, TensorboardBinaryClassificationExporter

# Number of cores the program is using
torch.set_num_threads(20)

database = '/Users/giuliacrocioni/remote_snellius/data/pMHCI/gnn_hdf5/rd.hdf5'
node_features = ["bsa", "depth", "hb_acceptors", "hb_donors", "hse", "ic", "pssm", "polarity", "sasa", "size", "type"]
edge_features = ["coulomb", "covalent", "dist", "vanderwaals"]

metrics_output_directory = "reports/"
metrics_exporters = [OutputExporter(metrics_output_directory),                TensorboardBinaryClassificationExporter(metrics_output_directory)]

if __name__ == '__main__':

    # creating HDF5DataSet object and selecting molecules, node/edge features, target, and clustering method:
    dataset = HDF5DataSet(
        root = "./",
        database = database,
        node_feature = node_features,
        edge_feature = edge_features,
        target = "binary",
        clustering_method = "mcl"
    )

    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

    nn = NeuralNet(
        dataset,
        GINet,
        task = "class",
        batch_size = 16,
        percent = [0.8, 0.2],
        metrics_exporters = metrics_exporters
    )

    nn.train(nepoch = 10, validate = True)
```

Data can be found on Snellius at `/projects/0/einf2380/data/pMHCI/gnn_hdf5/rd.hdf5`.

Error I get:

```

Traceback (most recent call last):
  File "/Users/giuliacrocioni/Desktop/eScience/projects_2022/3D-vac/3D-Vac/src/models/gnn_training.py", line 100, in <module>
    nn.train(nepoch = 10, validate = True)
  File "/Users/giuliacrocioni/Desktop/eScience/projects_2022/3D-vac/deeprank-core/deeprankcore/NeuralNet.py", line 301, in train
    self.eval(self.train_loader, 0, "training")
  File "/Users/giuliacrocioni/Desktop/eScience/projects_2022/3D-vac/deeprank-core/deeprankcore/NeuralNet.py", line 441, in eval
    self._metrics_exporters.process(
  File "/Users/giuliacrocioni/Desktop/eScience/projects_2022/3D-vac/deeprank-core/deeprankcore/models/metrics.py", line 54, in process
    metrics_exporter.process(pass_name, epoch_number, entry_names, output_values, target_values)
  File "/Users/giuliacrocioni/Desktop/eScience/projects_2022/3D-vac/deeprank-core/deeprankcore/models/metrics.py", line 122, in process
    roc_auc = roc_auc_score(target_values, probabilities)
  File "/Users/giuliacrocioni/miniforge3/envs/3d_vac/lib/python3.10/site-packages/sklearn/metrics/_ranking.py", line 546, in roc_auc_score
    y_score = check_array(y_score, ensure_2d=False)
  File "/Users/giuliacrocioni/miniforge3/envs/3d_vac/lib/python3.10/site-packages/sklearn/utils/validation.py", line 800, in check_array
    _assert_all_finite(array, allow_nan=force_all_finite == "allow-nan")
  File "/Users/giuliacrocioni/miniforge3/envs/3d_vac/lib/python3.10/site-packages/sklearn/utils/validation.py", line 114, in _assert_all_finite
    raise ValueError(
ValueError: Input contains NaN, infinity or a value too large for dtype('float64').
```

**Comment by cbaakman** [comment]
Something went wrong it the preprocessing. This change should fix it: https://github.com/DeepRank/deeprank-core/pull/113
