### ISSUE TITLE
`AttributeError` when calling `write_as_grid_to_hdf5`

### ISSUE THREAD

**Issue by gcroci2** [DeepRank/deeprank-core#431]
I am regenerating data including grids as well. But for _each_ data point, the mapped grids are not saved and I get this error:

```python
Graph/Query with ID residue-ppi:M-P:BA-42499 ran into an Exception (AttributeError: 'tuple' object has no attribute 'sizes'), and it has not been written to the hdf5 file. More details below:
'tuple' object has no attribute 'sizes'
Traceback (most recent call last):
  File "/gpfs/home1/ccrocion/repositories/deeprank-core/deeprankcore/query.py", line 248, in _process_one_query
    graph.write_as_grid_to_hdf5(output_path, grid_settings, grid_map_method)
  File "/gpfs/home1/ccrocion/repositories/deeprank-core/deeprankcore/utils/graph.py", line 293, in write_as_grid_to_hdf5
    grid = Grid(id_, self.center.tolist(), settings)
  File "/gpfs/home1/ccrocion/repositories/deeprank-core/deeprankcore/utils/grid.py", line 94, in __init__
    self._set_mesh(self._center, settings)
  File "/gpfs/home1/ccrocion/repositories/deeprank-core/deeprankcore/utils/grid.py", line 101, in _set_mesh
    half_size_x = settings.sizes[0] / 2
AttributeError: 'tuple' object has no attribute 'sizes'

```

To reproduce, see the pdb file attached, and this the code:

```python
from deeprankcore.query import QueryCollection
from deeprankcore.utils.grid import GridSettings, MapMethod
from deeprankcore.query import ProteinProteinInterfaceResidueQuery as PPIQuery

interface_distance_cutoff = 15  # max distance in Å between two interacting residues/atoms of two proteins
feature_modules = ['components',
		   'contact',
		   'exposure',
		   'irc',
		   'surfacearea']
combine_output = False
grid_settings = GridSettings( # None if you don't want grids
	# the number of points on the x, y, z edges of the cube
	points_counts = [35, 30, 30],
	# x, y, z sizes of the box in Å
	sizes = [1.0, 1.0, 1.0]),
grid_map_method = MapMethod.GAUSSIAN # None if you don't want grids

queries = QueryCollection()

queries.add(
       PPIQuery(
              pdb_path = "BA-42499.pdb", 
              chain_id1 = "M",
              chain_id2 = "P",
              distance_cutoff = interface_distance_cutoff))

queries.process(
       'test',
       feature_modules = feature_modules,
       combine_output = combine_output,
       grid_settings = grid_settings,
       grid_map_method = grid_map_method)
```
[BA-42499.pdb.zip](https://github.com/DeepRank/deeprank-core/files/11556342/BA-42499.pdb.zip)

**Comment by cbaakman** [comment]
Remove the comma at line 16.

**Comment by gcroci2** [comment]
> Remove the comma at line 16 of your example. After that, it works.

It does. I feel stupid but I am glad it's such a naive error :D
